application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      commerce-cif-graphql-integration-reference:
        license: Apache-2.0
        actions:
          dispatcher:
            function: actions/local/dispatcher.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              use-aio-cache: false
              url: 'https://a-dummy-url.com'
              remoteSchemas:
                cart:
                  order: 20
                  action: commerce-cif-graphql-integration-reference/cart
            annotations:
              provide-api-key: true
              final: true
          cart:
            function: actions/remote/cartResolver.js
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: info
          cif-schema:
            function: actions/documentation/introspection.js
            runtime: 'nodejs:14'
            web: 'yes'
            annotations:
              final: true
          import:
            function: actions/import/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              final: true
          test:
            function: actions/test/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              final: true
